--등급
CREATE TABLE HOMESHOPPING_USER_TIRE(
	tire VARCHAR2(300) PRIMARY KEY,
	max_price NUMBER NOT NULL,
	min_price NUMBER NOT NULL
);

--사용자
CREATE TABLE HOMESHOPPING_USER(
	ID VARCHAR2(300) PRIMARY KEY,
	PASSWORD VARCHAR2(200) NOT NULL,
	NAME VARCHAR2(200) NOT NULL,
	ADDRESS VARCHAR2(300) NOT NULL,
	TELEPHONE VARCHAR2(200) NOT NULL,
	EMAIL VARCHAR2(400) NOT NULL,
	TOTAL_PURCHASE NUMBER DEFAULT 0 NOT NULL
);

--주문
CREATE TABLE HOMESHOPPING_ORDER(
 order_no NUMBER PRIMARY KEY,
 order_date DATE NOT NULL,
 recipient_name VARCHAR2(300) NOT NULL,
 recipient_address VARCHAR2(300) NOT NULL,
 recipient_telephone VARCHAR2(300)NOT NULL,
 id VARCHAR2(300) NOT NULL
 CONSTRAINT homeshopping_order_fk REFERENCES HOMESHOPPING_USER(id) ON DELETE CASCADE 
);


--상품
CREATE TABLE HOMESHOPPING_PRODUCT(
	 product_no NUMBER PRIMARY KEY,
	 product_name VARCHAR2(300) NOT NULL,
	 product_price NUMBER NOT NULL,
	 product_content CLOB NOT NULL,
	 product_main_img VARCHAR2(300),
	 product_possesion_count NUMBER DEFAULT 0 NOT NULL ,
	 product_date DATE NOT NULL,
	 product_total_sale NUMBER DEFAULT 0 NOT NULL 
)

--주문 상세
CREATE TABLE HOMESHOPPING_ORDER_DETAIL(
	order_no NUMBER NOT NULL,
	product_no NUMBER NOT NULL, 
	order_count NUMBER NOT NULL,
	order_price NUMBER NOT NULL,
	CONSTRAINT HOMESHOPPING_ORDER_DETAIL_pk PRIMARY KEY (order_no,product_no),
	CONSTRAINT ORDER_DETAIL_ORDER_NO_FK FOREIGN KEY(order_no) REFERENCES HOMESHOPPING_ORDER(order_no) ON DELETE CASCADE ,
	CONSTRAINT PRODUCT_PRODUCT_NO_FK FOREIGN KEY(product_no) REFERENCES HOMESHOPPING_PRODUCT(product_no) ON DELETE CASCADE 
)
--쇼핑백
CREATE TABLE shopping_basket(
	product_no NUMBER NOT NULL,
	id VARCHAR2(300) NOT NULL,
	shopping_basket_count NUMBER NOT NULL,
	shopping_basket_price NUMBER NOT NULL,
	CONSTRAINT shopping_pk PRIMARY KEY (product_no,id),
	CONSTRAINT shopping_product_no_pk FOREIGN KEY(product_no) REFERENCES HOMESHOPPING_PRODUCT(product_no) ON DELETE CASCADE ,
	CONSTRAINT shopping_id_pk FOREIGN KEY(id) REFERENCES HOMESHOPPING_USER(id) ON DELETE CASCADE 
)

--시퀀스 생성
--주문
CREATE SEQUENCE order_no_seq; 
--상품
CREATE SEQUENCE product_no_seq; 


--테이블 삭제
DROP TABLE HOMESHOPPING_USER_TIRE;
DROP TABLE HOMESHOPPING_USER;
DROP TABLE HOMESHOPPING_ORDER;
DROP TABLE HOMESHOPPING_PRODUCT;
DROP TABLE HOMESHOPPING_ORDER_DETAIL;
DROP TABLE shopping_basket;


SELECT PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_MAIN_IMG,PRODUCT_POSSESION_COUNT,TO_CHAR(PRODUCT_DATE,'YYYY/MM/DD') AS 등록일,PRODUCT_TOTAL_SALE
FROM HOMESHOPPING_PRODUCT

SELECT ID,PASSWORD,NAME,ADDRESS,TELEPHONE,EMAIL,TOTAL_PURCHASE FROM HOMESHOPPING_USER
WHERE ID LIKE '%user%'




--상품 샘플 DB
INSERT INTO HOMESHOPPING_PRODUCT(PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_CONTENT,product_main_img,product_possesion_count,PRODUCT_DATE) VALUES(
order_no_seq.NEXTVAL,'테스트상품1',13500,'테스트상품내용입니다','resources/img/product/main/product_test.jpg',0,SYSDATE
);

SELECT * FROM HOMESHOPPING_PRODUCT;

SELECT TO_CHAR(PRODUCT_DATE,'YYYY/MM/DD') FROM HOMESHOPPING_PRODUCT


SELECT PRODUCT_NO,PRODUCT_NAME,PRODUCT_PRICE,PRODCUT_IMG_PATH,PRODUCT_COUNT,PRODUCT_KINDS_NAME,PRODUCT_NEW,TO_CHAR(PRODUCT_DATE,'YYYY/MM/DD') AS 등록일 FROM HOMESHOPPING_PRODUCT

